In [30]:
import numpy as np

In [31]:
arr1 = np.array([1,2,3])
arr1

array([1, 2, 3])

In [32]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

ND：最左边有N个[，只允许同类型元素

# 一、返回数组属性

### 1.打印数组维度：

In [39]:
print(arr1.ndim)
print(arr2.ndim)

1
2


### 2.返回元组，打印各个维度的元素的个数：

In [34]:
print(arr1.shape)
print(arr2.shape)

(3,)
(2, 3)


### 3.返回数组中元素的总个数

In [37]:
print(arr1.size)
print(arr2.size)

3
6


### 4.返回数组元素的类型

In [38]:
print(arr1.dtype)
print(arr2.dtype)

int64
int64


# 二、创建数组方法

### 1.创建元素全部为0的数组

In [40]:
np.zeros(3)

array([0., 0., 0.])

### 2.创建元素全部为1的数组

In [41]:
np.ones(5)

array([1., 1., 1., 1., 1.])

### 3.创建元素为数字序列的数组

In [42]:
np.arange(5,10,2)

array([5, 7, 9])