# 索引、切片、方法、提取

#### 写出导入numpy的语句，并且给numpy别名为np。

In [1]:
import numpy as np

#### 创建arr1为包含了元素1、3、2、4、9的数组，创建arr2为长度为5的由1组成的一维数组，arr3为长度为3的由0组成的一维数组。

In [3]:
arr1 = np.array([1,3,2,4,9])
arr2 = np.array([1,1,1,1,1])
arr3 = np.array([0,0,0])

#### 创建数组arr4，包括所有arr1、arr2、arr3里面的数字，并输出。

In [5]:
arr4 = np.concatenate([arr1,arr2,arr3])
arr4

array([1, 3, 2, 4, 9, 1, 1, 1, 1, 1, 0, 0, 0])

#### 更改arr1，对arr1里的元素进行排序，并输出排序后的结果。

In [6]:
arr1.sort()
arr1

array([1, 2, 3, 4, 9])

#### 用两种方法打印arr1的第三个元素。

In [18]:
arr1[2]

np.int64(3)

In [19]:
arr1[-3]

np.int64(3)

#### 输出从arr1第2个元素到第4个元素组成的的数组。

In [9]:
arr1[1:4]

array([2, 3, 4])

#### 输出arr1与arr2的同位置元素相加后组成的数组。

In [10]:
arr1 + arr2

array([ 2,  3,  4,  5, 10])

#### 输出arr1的各个元素乘以-5后组成的数组。

In [11]:
arr1 * (-5)

array([ -5, -10, -15, -20, -45])

#### 打印arr1数组的最大值、最小值、和、平均值。

In [12]:
arr1.max()

np.int64(9)

In [13]:
arr1.min()

np.int64(1)

In [14]:
arr1.sum()

np.int64(19)

In [15]:
arr1.mean()

np.float64(3.8)

#### 筛选出arr1数组里所有小于1或大于3的数字，并打印出来。

In [20]:
arr1<1

array([False, False, False, False, False])

In [16]:
arr1[(arr1<1)|(arr1>3)]

array([4, 9])