In [1]:
import numpy as np

## 一.连接数组

In [2]:
arr1 = np.array([5,17,3,26,31])
arr2 = np.array([2])
np.concatenate([arr1,arr2])

array([ 5, 17,  3, 26, 31,  2])

In [6]:
arr3 = np.ones(3)
np.concatenate([arr1,arr2,arr3])

array([ 5., 17.,  3., 26., 31.,  2.,  1.,  1.,  1.])

## 二、数组排序

#### 1.Numpy的sort函数

In [9]:
print(np.sort(arr1))
print(arr1)

[ 3  5 17 26 31]
[ 5 17  3 26 31]


#### 2.Python内置的sort方法

In [19]:
arr1.sort()
print(arr1)

None
[ 3  5 17 26 31]


## 三、获取元素

#### 1.用索引获得部分数组

In [20]:
arr1[0]

np.int64(3)

#### 2.用切片获得部分数组

In [21]:
arr1[1:4]

array([ 5, 17, 26])

## 四、数组运算

#### 1.数组和数组进行运算：

In [27]:
arr4 = np.array([1,1,4,5,1,4])
arr5 = np.array([7,2,5,5,1,7])

In [28]:
arr4 + arr5

array([ 8,  3,  9, 10,  2, 11])

In [29]:
arr5 - arr4

array([6, 1, 1, 0, 0, 3])

In [30]:
arr4 * arr5

array([ 7,  2, 20, 25,  1, 28])

In [31]:
arr5 / arr4

array([7.  , 2.  , 1.25, 1.  , 1.  , 1.75])

#### 2.数组和数据进行运算：

In [32]:
arr4 * 3

array([ 3,  3, 12, 15,  3, 12])

广播机制是科学计算库（如NumPy）中的一种重要特性，它允许不同形状的数组进行数学运算，而无需显式复制数据。  
基本规则：当两个数组进行运算时，广播机制按以下规则处理形状不匹配的情况：  
1.从尾部维度开始比较  
2.维度相等或其中一个为1时兼容  
3.缺失维度自动补1  

#### 3.聚合运算方法（通过一组值得到一个值）：

In [34]:
arr5.max()

np.int64(7)

In [35]:
arr5.min()

np.int64(1)

In [36]:
arr5.sum()

np.int64(27)

In [38]:
arr5.mean()

np.float64(4.5)

#### 4.根据条件筛选数组元素

In [39]:
arr5[arr5 > 4]

array([7, 5, 5, 7])

与：and：&  
或：or ：|  
非：not：~

In [42]:
arr4[(arr4>3)&(arr4<6)]

array([4, 5, 4])