In [12]:
import numpy as np

In [13]:
arr1 = np.array([6,2,-7,2,8,-2,1])
arr1

array([ 6,  2, -7,  2,  8, -2,  1])

In [14]:
arr2 = np.array([[1,3,5],[2,4,6]])
arr2

array([[1, 3, 5],
       [2, 4, 6]])

In [15]:
print(arr1.ndim)
print(arr2.ndim)

1
2


In [16]:
print(arr1.shape)
print(arr2.shape)

(7,)
(2, 3)


In [17]:
print(arr1.size)
print(arr2.size)

7
6


In [18]:
print(arr1.dtype)
print(arr2.dtype)

int64
int64


In [20]:
arr_all_0 = np.zeros(6)
arr_all_1 = np.ones(6)
arr_even = np.arange(10,21,2)
arr_all_0
arr_all_1
arr_even

array([10, 12, 14, 16, 18, 20])